# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a60871a8009ccfe6e8b684fd732c30957d3a70f8354848b75c1d9c524a2f141595d6e821549402e5e5ab724373814dc215638d6677abbe8539dc7bfcf1f8560e

test:
  secret_key_base: 885c4fb126f6f87a70835f68cdf06393b1b103aea5756a168b03948fd90d2cf230e8ae82aa04ef82ba71a06e6cfed376938d7c81b5b031ae65f57e8becac2e0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
